### ISSUE TITLE
Credstash has a method to list all secrets

### ISSUE THREAD

**Issue by DavidTanner** [roylines/node-credstash#13]
Credstash fetches a list of all secrets in DynamoDB and returns the names and versions of all credentials. 
https://github.com/fugue/credstash/blob/v1.11.0/credstash.py#L167

This would address #8 in the same way that credstash does, do a list then search for matching keys and get them afterwards.
https://github.com/fugue/credstash/blob/v1.11.0/credstash.py#L579

PR forthcoming

**Comment by toadkicker** [comment]
#8 is a dupe of this then
