### ISSUE TITLE
Overriding AWS.config.region with default

### ISSUE THREAD

**Issue by coltonone20** [roylines/node-credstash#27]
Seems to me this line in secrets.js will overwrite the value of AWS.config.region with the default region, even if a region other than the default was intentionally configured:

https://github.com/roylines/node-credstash/blob/155081a1975eb4fe729a097650583f4cd70cb7cf/lib/secrets.js#L5

Unless I am misunderstanding this behavior, I think the best think to do would be check if AWS.config.region is already set before overwriting it.

**Comment by roylines** [comment]
Happy to take a pull request on this one. Would you like to add a test and a fix?

**Comment by coltonone20** [comment]
yeap!
